// extension/src/pages/SveltePanel/src/panel/src/PanelComponents/StateModifier/StateModifier.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import sendMessageToChrome from '../../../../../../../messenger';

  import { addNewEvent } from '../../Store/timedEvents';

  export let componentId: number;
  export let stateKey: any;
  export let initValue;

  let inputValue = String(initValue);
  let editing = false;

  async function handleSubmit() {
    try {
      const newState = { [stateKey]: inputValue };
      const [tab] = await chrome.tabs.query({
        active: true,
        lastFocusedWindow: true,
      });
      // Assuming Redux-like store management is adapted for Svelte
      addNewEvent({
        type: 'sendMessage',
        data: performance.now(),
      });
      sendMessageToChrome('injectState', {
        tab,
        componentId,
        newState,
      });
      editing = false;
    } catch (err) {
      console.error(err);
    }
  }

  function handleKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      handleSubmit();
    }
  }

  function handleChange(event: Event) {
    const input = event.target as HTMLInputElement;
    inputValue = input.value;
  }
</script>

<div class="state-modifier">
  {#if editing}
    <input
      class="state-mod-input"
      type="text"
      value={inputValue}
      on:blur={handleSubmit}
      on:keydown={handleKeyPress}
      on:input={handleChange}
      placeholder={inputValue}
    />
  {:else}
    <div
      class="state-display"
      on:click={() => {
        editing = true;
      }}
      data-testid={`modifier-${stateKey}`}
      aria-label="Modifiable State"
    >
      <p>{inputValue !== '' ? inputValue : '""'}</p>
    </div>
  {/if}
</div>

<style>
  .state-modifier {
    margin-left: 0.5rem;
  }

  .state-display {
    cursor: pointer;
    text-align: center;
    color: #ff6ce9;
    font-family: Menlo, monospace;
  }

  .state-mod-input {
    display: none;
  }
</style>

// extension/src/pages/Panel/PanelComponents/StateModifier/StateModifier.tsx
import React, { ChangeEvent, useRef, useState } from 'react';
import './StateModifier.css';
import sendMessageToChrome from '../../../../messenger';
import { useDispatch } from 'react-redux';

interface StateModifierProps {
  componentId: number;
  stateKey: string;
  initValue: number | string;
}
/*
  The StateModifier component is a modifiable piece of state for the 
  selected component. When the user clicks on it, the text transforms into 
  a text input field. Then when the user and hits enter, or clicks 
  somewhere else, the text in the input field gets injected into the
  Svelte component
*/
const StateModifier = ({
  componentId,
  stateKey,
  initValue,
}: StateModifierProps) => {
  const [inputValue, setInputValue] = useState(String(initValue));
  const input = useRef<HTMLInputElement>(null);
  const display = useRef<HTMLInputElement>(null);

  const dispatch = useDispatch();

  function handleClickToEdit() {
    if (display.current === null || input.current === null) return;
    display.current.style.display = 'none';
    input.current.style.display = 'block';
    input.current.focus();
    input.current.select();
  }

  function finishEdit() {
    if (!display.current || !input.current) return;
    display.current.style.display = 'block';
    input.current.style.display = 'none';
  }

  async function handleSubmit() {
    try {
      const newState = { [stateKey]: inputValue };
      const [tab] = await chrome.tabs.query({
        active: true,
        lastFocusedWindow: true,
      });
      dispatch({
        type: 'timedEvents/addNewEvent',
        payload: {
          type: 'sendMessage',
          data: performance.now(),
        },
      });
      sendMessageToChrome('injectState', {
        tab: tab,
        componentId,
        newState,
      });
      finishEdit();
    } catch (err) {
      console.log(err);
    }
  }

  function handleKeyPress(e: React.KeyboardEvent<HTMLDivElement>) {
    // Losing focus will call handleSubmit()
    if (e.code === 'Enter' && input.current !== null) input.current.blur();
  }

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    setInputValue(e.target.value);
  }

  return (
    <div className="state-modifier">
      <div>
        <input
          aria-label="New State Input"
          className="state-mod-input"
          onKeyDown={handleKeyPress}
          ref={input}
          onBlur={handleSubmit}
          onChange={handleChange}
          placeholder={String(inputValue)}
        />
      </div>
      <div
        aria-label="Modifiable State"
        data-testid={`modifier-${stateKey}`}
        className="state-display"
        onClick={handleClickToEdit}
      >
        <p ref={display}>{inputValue !== '' ? inputValue : '""'}</p>
      </div>
    </div>
  );
};

export default StateModifier;
