// extension/src/pages/Panel/PanelPages/ListPage.tsx
import React from 'react';
import '../Panel.css';
import TreeComponent from '../PanelComponents/TreeComponent';
import { ComponentPageProps } from '../Panel';

// The page for List visualization
const ListPage: React.FC<ComponentPageProps> = ({
  rootComponentData,
}: ComponentPageProps) => {
  return (
    <div className="pane-content">
      <div id="root-container" data-testid="root-container">
        {rootComponentData && (
          <TreeComponent
            componentData={rootComponentData}
            level={1}
            key={rootComponentData.id}
          />
        )}
      </div>
    </div>
  );
};

export default ListPage;

// extension/src/pages/SveltePanel/src/panel/src/PanelPages/ListPage/ListPage.svelte
<script lang="ts">
  import TreeComponent from '../../PanelComponents/TreeComponent/TreeComponent.svelte';
  import { Snapshot } from '../../types';

  export let rootComponentData: Snapshot;
</script>

<div class="pane-content">
  <div id="root-container" data-testid="root-container">
    {#if rootComponentData.rootComponent}
      <TreeComponent componentData={rootComponentData.rootComponent} level={1} />
    {/if}
  </div>
</div>

<style>
#root-container {
  padding-top: 2rem;
  padding-bottom: 2rem;
}

</style>
