// extension/src/pages/SveltePanel/src/panel/src/PanelComponents/StateValue/StateValue.svelte
<script lang="ts">
  import StateModifier from '../StateModifier/StateModifier.svelte';
  import Highlight from "svelte-highlight";
  import typescript from "svelte-highlight/languages/typescript";

  export let value;
  export let stateKey;
  export let componentId;
  export let isArray;

  // Function to replace tabs with spaces for better formatting in code blocks
  function replaceTabsWithSpaces(string: string): String {
    return string.replace(/\t/g, '  ');
  }
</script>

<div class="property-item" data-testid={`state-value-${stateKey}`}>
  {#if Array.isArray(value)}
    <details class="state-value-array">
      <summary class="state-value-summary">Array [{value.length}]</summary>
      <ul>
        {#each value as item, index}
          <li class="component-info-array-list-item">
            <svelte:self {item} {stateKey} {componentId} isArray={true} />
          </li>
        {/each}
      </ul>
    </details>
  {:else if value === null}
    'null'
  {:else if value === false}
    'false'
  {:else if value === true}
    'true'
  {:else if typeof value === 'number' || typeof value === 'string'}
    {#if !isArray}
      <StateModifier {componentId} {stateKey} initValue={value} />
    {:else}
      <div>{value}</div>
    {/if}
  {:else if typeof value === 'object'}
    {#if 'isFunction' in value && value.__isFunction}
      <div>
        <details>
          <summary class="constant-property state-value-summary">function</summary>
          <div class="function-definition">
            <Highlight language={typescript} code={replaceTabsWithSpaces(value.source)} />
          </div>
        </details>
      </div>
    {/if}
  {/if}
</div>

<style>
.property-item {
  margin-left: 0.25rem;
}

li .component-info-array-list-item {
  margin-bottom: 0;
  list-style: none;
}

.state-value-summary {
  /* color: rgb(117, 117, 255); */
  color: rgb(207, 142, 253);
}

.function-definition {
  padding-right: 1rem;
}

/*react-syntax-highligher was enforcing overflow-x. This was creating
an ugly effect when expanding the window */
.code-block {
  overflow: visible !important;
}

</style>

// devtool/src/pages/Panel/PanelComponents/StateValue.tsx
import StateModifier from './StateModifier';
import './StateValue.css';

interface StateValueProps {
  value: any;
  stateKey: string;
  componentId: number;
  isArray: boolean;
}
/*
  Each item under State and Props on the right side of the app is a StateValue
  This component displays information about the item, and allows you to
  modify it if the data type is modifiable
*/
export const StateValue = ({
  value,
  stateKey,
  componentId,
  isArray,
}: StateValueProps) => {
  return (
    <div
      key={value}
      className="property-item"
      data-testid={`state-value-${stateKey}`}
    >
      {Array.isArray(value) ? (
        <details className="state-value-array">
          <summary className="state-value-summary">{`Array [${value.length}]`}</summary>
          <ul>
            {/* Render an un-modifiable StateValue component if this data type
            can not be modified */}
            {value.map((i: any, index: number) => {
              return (
                <li
                  className="component-info-array-list-item"
                  key={`id-${componentId}-value-${index}`}
                >
                  <StateValue
                    stateKey={stateKey}
                    value={i}
                    componentId={componentId}
                    isArray={true}
                  />
                </li>
              );
            })}
          </ul>
        </details>
      ) : value === null ? (
        'null'
      ) : value === false ? (
        'false'
      ) : value === true ? (
        'true'
      ) : typeof value === 'number' || typeof value === 'string' ? (
        // Render a StateModifier component if this data type can be modified
        !isArray ? (
          <StateModifier
            componentId={componentId}
            stateKey={stateKey}
            initValue={value}
          />
        ) : (
          <div>{value}</div>
        )
      ) : typeof value === 'object' ? (
        value.hasOwnProperty('__isFunction') && value.__isFunction === true ? (
          <details>
            <summary className="constant-property state-value-summary">
              function {stateKey}()
            </summary>
            {value.source}
          </details>
        ) : null
      ) : null}
    </div>
  );
};
