// extension/src/pages/SveltePanel/src/panel/src/PanelComponents/StateModifier/StateModifier.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import sendMessageToChrome from '../../../../../../../messenger';

  import { addNewEvent } from '../../Store/timedEvents';

  export let componentId: number;
  export let stateKey: any;
  export let initValue;

  let inputValue = String(initValue);
  let editing = false;

  async function handleSubmit() {
    try {
      const newState = { [stateKey]: inputValue };
      const [tab] = await chrome.tabs.query({
        active: true,
        lastFocusedWindow: true,
      });
      // Assuming Redux-like store management is adapted for Svelte
      addNewEvent({
        type: 'sendMessage',
        data: performance.now(),
      });
      sendMessageToChrome('injectState', {
        tab,
        componentId,
        newState,
      });
      editing = false;
    } catch (err) {
      console.error(err);
    }
  }

  function handleKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      handleSubmit();
    }
  }

  function handleChange(event: Event) {
    const input = event.target as HTMLInputElement;
    inputValue = input.value;
  }
</script>

<div class="state-modifier">
  {#if editing}
    <input
      class="state-mod-input"
      type="text"
      value={inputValue}
      on:blur={handleSubmit}
      on:keydown={handleKeyPress}
      on:input={handleChange}
      placeholder={inputValue}
    />
  {:else}
    <div
      class="state-display"
      on:click={() => {
        editing = true;
      }}
      data-testid={`modifier-${stateKey}`}
      aria-label="Modifiable State"
    >
      <p>{inputValue !== '' ? inputValue : '""'}</p>
    </div>
  {/if}
</div>

<style>
  .state-modifier {
    margin-left: 0.5rem;
  }

  .state-display {
    cursor: pointer;
    text-align: center;
    color: #ff6ce9;
    font-family: Menlo, monospace;
  }

  .state-mod-input {
    display: none;
  }
</style>

// devtool/src/pages/Panel/PanelComponents/StateModifier.tsx
import React, { ChangeEvent, useRef, useState } from 'react';
import './StateModifier.css';

interface StateModifierProps {
  componentId: number;
  stateKey: string;
  initValue: number | string;
}

const StateModifier = ({
  componentId,
  stateKey,
  initValue,
}: StateModifierProps) => {
  const [inputValue, setInputValue] = useState(initValue);
  const input = useRef<HTMLInputElement>(null!);
  const display = useRef<HTMLInputElement>(null!);

  function handleKeyPress(e: React.KeyboardEvent<HTMLDivElement>) {
    if (e.code !== 'Enter') return;
    handleSubmit();
  }

  function handleClickToEdit() {
    display.current.style.display = 'none';
    input.current.style.display = 'block';
    input.current.focus();
    input.current.select();
  }

  async function handleSubmit() {
    const newState = { [stateKey]: inputValue };
    const [tab] = await chrome.tabs.query({
      active: true,
      lastFocusedWindow: true,
    });
    chrome.tabs.sendMessage(tab.id!, {
      message: 'injectState',
      componentId: componentId,
      newState: newState,
    });
  }

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    setInputValue(e.target.value);
  }

  return (
    <div className="state-modifier">
      <div>
        <input
          style={{ display: 'none' }}
          onKeyDown={handleKeyPress}
          ref={input}
          onBlur={handleSubmit}
          onChange={handleChange}
          placeholder={String(inputValue)}
        />
      </div>
      <div className="state-display" onClick={handleClickToEdit}>
        <p ref={display}>{inputValue !== '' ? inputValue : '""'}</p>
      </div>
    </div>
  );
};

export default StateModifier;
