// devtool/src/pages/Panel/Panel.tsx
import React, { useEffect } from 'react';
import './Panel.css';
import Split from 'react-split';
import ComponentInfo from './PanelComponents/ComponentInfo';
import Navbar from './PanelComponents/Navbar';
import { Routes, Route, useNavigate } from 'react-router-dom';
import TreePage from './PanelPages/TreePage';
import StepPage from './PanelPages/StepPage';
import { Component } from './slices/highlightedComponentSlice';
import { useSelector } from 'react-redux';
import { selectCurrentSnapshot, Snapshot } from './slices/currentSnapshotSlice';
import { useDispatch } from 'react-redux';
import { TreeHistory, selectTreeHistory } from './slices/treeHistorySlice';
import Rewinder from './PanelComponents/Rewinder';

export interface ComponentPageProps {
  rootComponentData: Component;
}

window.addEventListener('beforeunload', function() {
  chrome.runtime.sendMessage({message: "handleClosedPanel"});
});

function Panel() {
  const currentSnapshot: Snapshot = useSelector(selectCurrentSnapshot);
  const treeHistory: TreeHistory = useSelector(selectTreeHistory);
  const navigate = useNavigate();
  const dispatch = useDispatch();

  // Navigate to the root directory on page load
  useEffect(() => {
    navigate('/');
  }, []);

  useEffect(() => {
    async function setUpPanel() {
      const [tab] = await chrome.tabs.query({
        active: true,
        lastFocusedWindow: true,
      });
      chrome.tabs.sendMessage(tab.id!, { message: 'getRootComponent' });
    }
    setUpPanel();

    // I only want to add a listener once, so it goes in the set up useEffect
    // Listen for response from ContentScriptIsolated. This is where we
    // get the current tab's root Component, and update StepPage's state
    chrome.runtime.onMessage.addListener(function (
      message,
      sender,
      sendResponse
    ) {
      if (message.type === 'updateRootComponent') {
        const rootComponent = message.rootComponent;
        if (rootComponent) {
          createAndSaveNewSnapshot(rootComponent);
        }
      } else if (message.type === 'returnRootComponent') {
        const rootComponent = message.rootComponent;
        if (rootComponent) {
          createAndSaveNewSnapshot(rootComponent);
        } else {
          console.log('Error getting root component');
        }
        // For use after rewinding
      } else if (message.type === 'returnTempRoot') {
        const tempRoot = message.rootComponent;
        // set the tempRoot as the current snapshot without saving it
        dispatch({
          type: 'currentSnapshot/setCurrentSnapshot',
          payload: {
            rootComponent: tempRoot,
          },
        });
      }
    });
  }, []);

  function createAndSaveNewSnapshot(newRootComponent: Component) {
    console.log(
      'creating a new snapshot with this root node: ',
      newRootComponent
    );
    dispatch({
      type: 'currentSnapshot/setCurrentSnapshot',
      payload: {
        rootComponent: newRootComponent,
      },
    });
    dispatch({
      type: 'treeHistory/addNewSnapshot',
      payload: {
        newSnapshot: newRootComponent,
      },
    });
  }

  // Takes the snapshot in treeHistory[snapshotIndex] and injects state with all
  // of its component's state. Then the content script returns a "temp root component"
  // which gets displayed to the screen without saving a new snapshot
  async function changeSnapshot(snapshotIndex: number) {
    const [tab] = await chrome.tabs.query({
      active: true,
      lastFocusedWindow: true,
    });
    chrome.tabs.sendMessage(tab.id!, {
      message: 'injectSnapshot',
      snapshot: treeHistory.treeHistory[snapshotIndex],
    });
  }

  return (
    <div className="container">
      <div id="content">
        <Split className="split">
          <div className="pane">
            <Navbar />
            <Routes>
              <Route
                path="/"
                element={
                  <StepPage
                    rootComponentData={currentSnapshot.rootComponent!}
                  />
                }
              />
              <Route
                path="/tree"
                element={
                  <TreePage
                    rootComponentData={currentSnapshot.rootComponent!}
                  />
                }
              />
            </Routes>
          </div>
          <div className="pane">
            <ComponentInfo />
          </div>
        </Split>
      </div>
      <Rewinder
        changeSnapshot={changeSnapshot}
        numberOfSnapshots={treeHistory.treeHistory.length}
      />
    </div>
  );
}

export default Panel;

// extension/src/pages/SveltePanel/src/panel/src/PanelComponents/Panel/Panel.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import Navbar from '../Navbar/Navbar.svelte';
  import ComponentInfo from '../ComponentInfo/ComponentInfo.svelte';
  import TreePage from '../../PanelPages/TreePage/TreePage.svelte';
  import ListPage from '../../PanelPages/ListPage/ListPage.svelte';
  import Rewinder from '../Rewinder/Rewinder.svelte';
  import {
    currentSnapshot,
    treeHistory,
  } from '../../Store/store';
  import sendMessageToChrome from '../../../../../../../messenger';
  import { addNewSnapshot, deleteAllSnapshots } from '../../Store/treeHistory';
  import { setCurrentSnapshot } from '../../Store/currentSnapshot';
    import { addNewEvent } from '../../Store/timedEvents';
    import { get } from 'svelte/store';

  let unableToGetComponentData = false;
  let lastUpdateMessage = '';

  window.addEventListener('beforeunload', () => {
    sendMessageToChrome('handleClosedPanel');
  });

  window.addEventListener('message', (event: MessageEvent) => {
    const { type, rootComponent } = event.data;
    if (type === 'updateRootComponent' && rootComponent) {
      setCurrentSnapshot(rootComponent);
      addNewSnapshot(rootComponent);
    } else if (type === 'returnRootComponent') {
      if (!rootComponent) {
        unableToGetComponentData = true;
      } else {
        setCurrentSnapshot(rootComponent);
      }
    } else if (type === 'returnProfilingData') {
      lastUpdateMessage = `Last update took ${event.data.time}ms`;
    }
  });

  async function changeSnapshot(snapshotIndex: number) {
    try {
      console.log('chrome', chrome);
      const [tab] = await chrome.tabs.query({
        active: true,
        lastFocusedWindow: true,
      });
      addNewEvent({
          type: 'sendMessage',
          data: performance.now(),
        })
      sendMessageToChrome('injectSnapshot', {
        snapshot: get(treeHistory).treeHistory[snapshotIndex],
        tab,
      });
    } catch (err) {
      console.log('Error getting tab: ', err);
    }
  }

  function clearSnapshotHistory() {
    deleteAllSnapshots();
  }


  onDestroy(() => {
    window.removeEventListener('beforeunload', () => {});
    window.removeEventListener('message', () => {});
  });
</script>

<svelte:head>
  <link rel="stylesheet" href="./Panel.css" />
</svelte:head>

<div class="container" data-testid="panel">
  <div class="split">
    <div class="pane">
      <header>
        <Navbar />
      </header>
      {#if unableToGetComponentData}
        <h1 id="no-data-error" data-testid="no-data-error">
          Unable to get component data
        </h1>
      {:else}
        <nav>
          <div id="left-pane">
            <a href="/">
              <ListPage rootComponentData={get(currentSnapshot)} />
            </a>
            <a href="/tree">
              <TreePage rootComponentData={get(currentSnapshot)} />
            </a>
          </div>
        </nav>
        <p id="last-update-message">{lastUpdateMessage}</p>
      {/if}
    </div>
    <div>
      <ComponentInfo />
    </div>
  </div>
  <Rewinder
    {changeSnapshot}
    numberOfSnapshots={get(treeHistory).treeHistory.length}
    {clearSnapshotHistory}
  />
</div>
